events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://log_reg:6000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /veicoli/ {
            proxy_pass http://veicoli:7000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /polizze/ {
            proxy_pass http://polizze:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /sinistri/ {
            proxy_pass http://sinistri_user:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /periti/ {
            proxy_pass http://periti:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /assicurazione/ {
            proxy_pass http://init:9500/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}